package reponses;

/**
 * Enumération pour représenter la réponse positive ou le cas d'erreur.
 */
public enum VerifierResultat {
    CONFORME,
    VALEUR_EXTREME_INCORRECTE,
    MARQUE_DIFFERENTE,
    MARQUE_INCONNU,
    MODEL_INCONNU,
    LARGEUR_DIFFERENTE,
    VELO_CREE,
    VELO_INCONNU,
    POSITION_INCONNU,
    VELO_MODIFIE,
    VELO_SUPPRIME, 
    VALEUR_INCONNU,
    PNEU_INCONNU,
    NUMERO_SERIE_INVALIDE, 
    PUISSANCE_BATTERIE_INVALIDE,
    VELO_RECUPERE,
    ERREUR_FORMAT_JSON,
    ERREUR_LECTURE_FICHIER,
    NUMERO_SERIE_NON_UNIQUE,
    FICHIER_INTRROUVABLE,
    VELO_CREE_SANS_DOUBLON,
    USINE_MODIFIE, ERREUR_PNEUS, 
    VELO_RECUPERE_AVEC_NON_CONFORMITE,
    ELEMENT_MANQUANT_OU_VALEUR_NULLE,
    BATTERIE_INEXISTANTE,
    MARQUE_PNEU_DIFFERENTE
}
